# src\FB\SetManagerBundle\Resources\config\routing.yml
fb_setmanager_home:
    path:     /
    defaults: { _controller: FBSetManagerBundle:SetManager:index }

fb_setmanager_update:
    path:    /update/{id}
    defaults: { _controller: FBSetManagerBundle:SetManager:update }
    requirements:
        id: \d+

fb_setmanager_delete:
    path:   /delete/{id}
    defaults: { _controller: FBSetManagerBundle:SetManager:delete }
    requirements:
            id: \d+
