# src\FB\ClubManagerBundle\Resources\config\routing.yml
fb_clubmanager_home:
    path:     /
    defaults: { _controller: FBClubManagerBundle:Manager:index }

# temp rout for forum
fb_clubmanager_forum:
   path:    /clubmanager/forum
   defaults: { _controller: FBClubManagerBundle:Manager:forum }
