fb_clubmanager_home:
    path:     /
    defaults: { _controller: FBClubManagerBundle:Manager:index }

fb_clubmanager_view:
    path:    /clubmanager/view
    defaults: { _controller: FBClubManagerBundle:Manager:view }

