<?php

namespace FB\TournamentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    /**
     * @param $player
     * @return array|\Doctrine\ORM\QueryBuilder
     */
    function findByPlayers($player){
        $query = $this
            ->createQueryBuilder('a')
            ->select('a')
            ->leftJoin('a.players', 'c')
            ->addSelect('c');
        $query = $query->add('where', $query->expr()->in('c', ':c'))
            ->setParameter('c', $player)
            ->getQuery()
            ->getResult();
        return $query;
    }
}
