fb_tournament_home:
    path:     /
    defaults: { _controller: FBTournamentBundle:Tournament:index }

fb_tournament_add:
    path:     /add
    defaults: { _controller: FBTournamentBundle:Tournament:add }

fb_tournament_update:
    path:    /update/{id}
    defaults: { _controller: FBTournamentBundle:Tournament:update }
    requirements:
        id: \d+

fb_tournament_delete:
    path:    /delete/{id}
    defaults: { _controller: FBTournamentBundle:Tournament:delete }
    requirements:
        id: \d+

fb_tournament_calendar:
    path:   /calendar
    defaults: { _controller: FBTournamentBundle:Tournament:calendar }

fb_season_home:
    path:    /season
    defaults: { _controller: FBTournamentBundle:Season:index }

fb_season_update:
    path:   /season/update/{id}
    defaults: { _controller: FBTournamentBundle:Season:update }
    requirements:
        id: \d+
