fb_tournament_home:
    path:     /
    defaults: { _controller: FBTournamentBundle:Tournament:index }

fb_tournament_add:
    path:     /add
    defaults: { _controller: FBTournamentBundle:Tournament:add }

fb_tournament_update:
    path:    /update/{id}
    defaults: { _controller: FBTournamentBundle:Tournament:update }

fb_tournament_delete:
    path:    /delete/{id}
    defaults: { _controller: FBTournamentBundle:Tournament:delete }

fb_season_home:
    path:    /season
    defaults: { _controller: FBTournamentBundle:Season:index }

fb_season_add:
    path:   /season/add/
    defaults: { _controller: FBTournamentBundle:Season:add }

fb_season_update:
    path:   /season/update/{id}
    defaults: { _controller: FBTournamentBundle:Season:update }