fb_tournament:
    resource: "@FBTournamentBundle/Resources/config/routing.yml"
    prefix:   /tournament

fb_set_manager:
    resource: "@FBSetManagerBundle/Resources/config/routing.yml"
    prefix:   /set

fb_player_manager:
    resource: "@FBPlayerManagerBundle/Resources/config/routing.yml"
    prefix:   /player

fb_club_manager:
    resource: "@FBClubManagerBundle/Resources/config/routing.yml"
    prefix:   /

fb_user:
  resource:  "@FBUserBundle/Resources/config/routing.yml"
  prefix:    /

# SONATA ADMIN BUNDLE
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix:   /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:   /admin

# FOS Js Routing bundle
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# Calendar bundle
adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"