fb_tournament:
    resource: "@FBTournamentBundle/Resources/config/routing.yml"
    prefix:   /tournament

fb_set_manager:
    resource: "@FBSetManagerBundle/Resources/config/routing.yml"
    prefix:   /set

fb_player_manager:
    resource: "@FBPlayerManagerBundle/Resources/config/routing.yml"
    prefix:   /player

fb_club_manager:
    resource: "@FBClubManagerBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: FBUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout