# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    FB.TounamentBundle.calendar_listener:
      class: FB\TournamentBundle\EventListener\CalendarEventListener
      tags:
              - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }
      arguments: ['@doctrine.orm.entity_manager']