fb_session_home:
    path:     /
    defaults: { _controller: FBSessionManagerBundle:SessionManager:index }

fb_session_add:
    path:     /add
    defaults: { _controller: FBSessionManagerBundle:SessionManager:add }

fb_session_detail:
    path:     /detail/{id}
    defaults: { _controller: FBSessionManagerBundle:SessionManager:detail }
    requirements:
         id: \d+

fb_session_update:
    path:   /update/{id}
    defaults: { _controller: FBSessionManagerBundle:SessionManager:update }
    requirements:
        id: \d+

fb_session_delete:
    path:   /delete/{id}
    defaults: { _controller: FBSessionManagerBundle:SessionManager:delete }
    requirements:
        id: \d+

fb_session_team_add:
    path: /addteam
    defaults: { _controller: FBSessionManagerBundle:SessionManager:addTeam }
    requirements:
        id: \d+

fb_session_team_update:
    path: /updateteam/{id}
    defaults: { _controller: FBSessionManagerBundle:SessionManager:updateTeam }
    requirements:
        id: \d+