fb_session_home:
    path:     /
    defaults: { _controller: FBSessionManagerBundle:SessionManager:index }

fb_session_add:
    path:     /add
    defaults: { _controller: FBSessionManagerBundle:SessionManager:add }

fb_session_detail:
    path:     /detail/{id}
    defaults: { _controller: FBSessionManagerBundle:SessionManager:detail }
    requirements:
         id: \d+
