<?php

namespace FB\SetManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameSetRepository extends EntityRepository
{
}
