<?php

namespace FB\PlayerManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThrowStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThrowStatRepository extends EntityRepository
{
}
