services:
    app_user.form.registration.form.type:
        class: FB\UserBundle\Form\RegistrationType
        arguments: [%fos_user.model.user.class%]
        tags:
              - { name: form.type, alias: app_user_registration }