# src\FB\PlayerManagerBundle\Resources\config\routing.yml
fb_playermanager_home:
    path:     /
    defaults: { _controller: FBPlayerManagerBundle:PlayerManager:index }

fb_playermanager_add:
    path:    /add
    defaults: { _controller: FBPlayerManagerBundle:PlayerManager:add }

fb_playermanager_update:
   path:    /update/{id}
   defaults: { _controller: FBPlayerManagerBundle:PlayerManager:update }
   requirements:
        id: \d+

fb_playermanager_delete:
  path:    /delete/{id}
  defaults: { _controller: FBPlayerManagerBundle:PlayerManager:delete }
  requirements:
          id: \d+
